version: 2
updates:
- package-ecosystem: docker
  directory: "/tests"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
