repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-yaml
-   repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [file, rust]
        entry: cargo fmt -- --check

      - id: clippy
        name: clippy
        language: system
        types: [file, rust]
        entry: cargo clippy --all-targets --all -- -D warnings # Use -D warnings option to ensure the job fails when encountering warnings
        pass_filenames: false

      - id: test
        name: test
        language: system
        files: '\.rs$'
        entry: cargo test --lib
        pass_filenames: false

default_language_version:
    python: python3.7
