image: Visual Studio 2017
platform:
- x64
- x86

environment:
  matrix:
    - channel: stable
    - channel: nightly

install:
  - if [%PLATFORM%]==[x64] (
      set PLATFORM_PRETTY_NAME=x86_64
    )
  - if [%PLATFORM%]==[x86] (
      set PLATFORM_PRETTY_NAME=i686
    )
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - echo %PLATFORM_PRETTY_NAME%
  - rustup-init -yv --default-toolchain %channel% --default-host %PLATFORM_PRETTY_NAME%-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - set PATH=%PATH%;C:\Libraries\llvm-5.0.0\bin
  - rustc -vV
  - cargo -vV

build_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --verbose
    )
  - if [%APPVEYOR_REPO_TAG%]==[true] if [%channel%]==[nightly] (
      cargo build --release --features=alloc_system
    )
  - dir C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.12.25810\
  - if [%APPVEYOR_REPO_TAG%]==[true] if [%channel%]==[nightly] (
      7z a grcov-win-%PLATFORM_PRETTY_NAME%.tar .\target\release\grcov.exe "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.12.25810\%PLATFORM%\Microsoft.VC141.CRT\msvcp140.dll" "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.12.25810\%PLATFORM%\Microsoft.VC141.CRT\vcruntime140.dll"
    )
  - if [%APPVEYOR_REPO_TAG%]==[true] if [%channel%]==[nightly] (
      7z a grcov-win-%PLATFORM_PRETTY_NAME%.tar.bz2 grcov-win-%PLATFORM_PRETTY_NAME%.tar
    )

test_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo test --verbose
    )

artifacts:
  - path: grcov-win-$(PLATFORM_PRETTY_NAME).tar.bz2

deploy:
  artifact: grcov-win-$(PLATFORM_PRETTY_NAME).tar.bz2
  auth_token:
    secure: /BjmtIYmmvSDJ5939QEcd857vcA29dIlcb/u6wgbWkAm+Cp4LN2KTi3+cVveoqz+
  description: ''
  on:
    channel: nightly
    appveyor_repo_tag: true
  provider: GitHub
