image: Visual Studio 2017
platform:
- x64

environment:
  matrix:
    - CHANNEL: stable
      FEATURES:
      PLATFORM_TARGET: x86_64
      PLATFORM_VS: x64

    - CHANNEL: nightly
      FEATURES: alloc_system
      PLATFORM_TARGET: x86_64
      PLATFORM_VS: x64

    # TODO: The i686 build currently doesn't work.
    # - CHANNEL: nightly
    #   FEATURES: alloc_system
    #   PLATFORM_TARGET: i686
    #   PLATFORM_VS: x86

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %CHANNEL% --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - set PATH=%PATH%;C:\Libraries\llvm-5.0.0\bin
  - rustc -vV
  - cargo -vV
  - llvm-config --version
  - llvm-config --host-target
  - set TARGET=%PLATFORM_TARGET%-pc-windows-msvc
  - if NOT "%PLATFORM_TARGET%" == "x86_64" (
      rustup target add %TARGET%
    )
  - if [%APPVEYOR_REPO_TAG%]==[false] (set BUILD_TYPE=debug)
  - if [%APPVEYOR_REPO_TAG%]==[true] (set BUILD_TYPE=release)
  - if [%BUILD_TYPE%]==[debug] (set CARGO_RELEASE_ARG=)
  - if [%BUILD_TYPE%]==[release] (set CARGO_RELEASE_ARG=--release)

build_script:
  - cargo build %CARGO_RELEASE_ARG% --features=%FEATURES% --locked --target %TARGET%
  - 7z a grcov-win-%PLATFORM_TARGET%.tar .\target\%TARGET%\%BUILD_TYPE%\grcov.exe "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.14.26405\%PLATFORM_VS%\Microsoft.VC141.CRT\msvcp140.dll" "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.14.26405\%PLATFORM_VS%\Microsoft.VC141.CRT\vcruntime140.dll"
  - 7z a grcov-win-%PLATFORM_TARGET%.tar.bz2 grcov-win-%PLATFORM_TARGET%.tar

test_script:
  - cargo test %CARGO_RELEASE_ARG% --verbose

artifacts:
  - path: grcov-win-$(PLATFORM_TARGET).tar.bz2

deploy:
  artifact: grcov-win-$(PLATFORM_TARGET).tar.bz2
  auth_token:
    secure: /BjmtIYmmvSDJ5939QEcd857vcA29dIlcb/u6wgbWkAm+Cp4LN2KTi3+cVveoqz+
  description: ''
  on:
    CHANNEL: nightly
    appveyor_repo_tag: true
  provider: GitHub
