[package]
name = "grcov"
version = "0.3.2"
authors = ["Marco Castelluccio <mcastelluccio@mozilla.com>"]
description="Rust tool to collect and aggregate code coverage data for multiple source files"
license="MPL-2.0"
documentation="https://github.com/mozilla/grcov"
homepage="https://github.com/mozilla/grcov"
repository="https://github.com/mozilla/grcov"
readme = "README.md"
keywords=["coverage"]
categories=["command-line-utilities", "development-tools", "development-tools::testing"]
links = "llvmgcov"
build = "build.rs"
exclude = [
    "test/*",
    "tests/*",
    "benches/*",
    ".travis.yml",
    "appveyor.yml",
    ".gitignore",
]

[badges]
appveyor = { repository = "marco-c/grcov" }
travis-ci = { repository = "mozilla/grcov" }
codecov = { repository = "mozilla/grcov" }

[build-dependencies]
cc = "^1.0"

[dependencies]
crossbeam = "^0.4"
serde_json = "^1.0"
walkdir = "^2.2"
num_cpus = "^1.8"
semver = "^0.9"
md5 = "^0.6"
zip = { version = "^0.4", features = ["deflate-zlib"], default-features = false }
tempdir = "^0.3"
uuid = { version = "^0.7", features = ["v4"] }
libc = "^0.2"
globset = "^0.4"
xml-rs = "^0.8"

[dev-dependencies]
regex = "^1.0"
