[package]
name = "grcov"
version = "0.2.3"
authors = ["Marco Castelluccio <mcastelluccio@mozilla.com>"]
description="Rust tool to collect and aggregate code coverage data for multiple source files"
license="MPL-2.0"
documentation="https://github.com/mozilla/grcov"
homepage="https://github.com/mozilla/grcov"
repository="https://github.com/mozilla/grcov"
readme = "README.md"
keywords=["coverage"]
categories=["command-line-utilities", "development-tools", "development-tools::testing"]
links = "llvmgcov"
build = "build.rs"
exclude = [
    "test/*",
    "tests/*",
    "benches/*",
    ".travis.yml",
    "appveyor.yml",
    ".gitignore",
]

[badges]
appveyor = { repository = "https://github.com/mozilla/grcov" }
travis-ci = { repository = "https://github.com/mozilla/grcov" }
codecov = { repository = "https://github.com/mozilla/grcov" }

[build-dependencies]
cc = "^1.0"

[dependencies]
crossbeam = "^0.3"
serde_json = "^1.0"
walkdir = "^2.0"
num_cpus = "^1.7"
semver = "^0.9"
rust-crypto = "^0.2"
zip = { version = "^0.2", default-features = false }
tempdir = "^0.3"
uuid = { version = "^0.5", features = ["v4"] }
libc = "^0.2"
globset = "^0.3"
xml-rs = "^0.8"

[dev-dependencies]
regex = "^0.2"

[features]
# For the system allocator feature.
alloc_system = []
