[package]
name = "grcov"
version = "0.2.3"
authors = ["Marco Castelluccio <mcastelluccio@mozilla.com>"]
links = "llvmgcov"
build = "build.rs"

[build-dependencies]
cc = "^1.0"

[dependencies]
crossbeam = "^0.4"
serde_json = "^1.0"
walkdir = "^2.2"
num_cpus = "^1.8"
semver = "^0.9"
rust-crypto = "^0.2"
zip = { version = "^0.4", default-features = false }
tempdir = "^0.3"
uuid = { version = "^0.7", features = ["v4"] }
libc = "^0.2"
globset = "^0.4"
xml-rs = "^0.8"

[dev-dependencies]
regex = "^1.0"

[features]
# For the system allocator feature.
alloc_system = []
